### ISSUE TITLE
VeertuManage does not work when shell is in a virtualenv with python3

### ISSUE THREAD

**Issue by cnf** [veertuinc/vdhh#18]
```
$ /Applications/Veertu\ Desktop.app/Contents/SharedSupport/VeertuManage
Usage: cli_interface.py [OPTIONS] COMMAND [ARGS]...

Options:
  --machine-readable
  --help              Show this message and exit.

Commands:
  create
  delete    Deletes a VM
  describe  Show all data for a VM
  export    Exports a vm to a file
  import    Import a vm into Veertu
  list      Shows a list of VMs, ids and names
  modify    Modifys a VM settings
  pause     Pauses a VM
  reboot    Restarts a VM
  show      Show runtime VM state and properties.
  shutdown  Shuts down a vm
  start     Starts or resumes paused VM
$ workon SomePython3Project
$ /Applications/Veertu\ Desktop.app/Contents/SharedSupport/VeertuManage
Traceback (most recent call last):
  File "/Applications/Veertu Desktop.app/Contents/SharedSupport/cli/cli_interface.py", line 8, in <module>
    from veertu_manager import get_veertu_manager, VeertuManagerException, VeertuAppNotFoundException, VMNotFoundException, \
  File "/Applications/Veertu Desktop.app/Contents/SharedSupport/cli/veertu_manager.py", line 3, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
[1]    90652 exit 1     /Applications/Veertu\ Desktop.app/Contents/SharedSupport/VeertuManage

**Comment by kenji21** [comment]
Fixed this by editing VeertuManage shell script: 

````
diff /Applications/Veertu\ Desktop.app/Contents/SharedSupport/VeertuManage  /Applications/Veertu\ Desktop.app/Contents/SharedSupport/VeertuManage.orig
3c3
< python2.7 "$DIR/cli/cli_interface.py" "$@"
---
> python "$DIR/cli/cli_interface.py" "$@"
````
